version: '3.3'
services:
    monopoly-game:
        container_name: monopoly-game
        build:
            context: .
        environment:
          - PORT=8443
          - HTTP=false
          - HTTP_TLS_KEY=key.pem
          - HTTP_TLS_CERTIFICATE=cert.pem
        ports:
          - 8443:8443
        restart: unless-stopped
